services:
  - type: web
    name: codementor-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python back-end/app2.py"
    envVars:
      - key: COHERE_API_KEY
        value: "NKZD0sANta3S02GP5wCUYrPev7dRHW5WDbJFdbJ2"
