services:
  - type: web
    name: codementor-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python back-end/app2.py"
    setupCommands:
      - apt-get update && apt-get install -y build-essential libopenblas-dev
    envVars:
      - key: COHERE_API_KEY
        value: "NKZD0sANta3S02GP5wCUYrPev7dRHW5WDbJFdbJ2"
